services:
  parser:
    build: .
    container_name: product-parser
    volumes:
      - ./output:/root/output
    environment:
      - OUTPUT_DIR=/root/output
      - BASE_URL=https://kuper.ru
      - PROXY_URL=${PROXY_URL:-}
      - CATEGORIES=${CATEGORIES:-1,2}
      - STORE_ID=${STORE_ID:-}
    command: ["-categories=1,2", "-output=/root/output"]